version: "2.4"
services:
 amr-base:
  image: amr_miniprj:1.0
  environment:
      ROS_IP: 127.0.0.1
      ROS_HOSTNAME: 127.0.0.1
      ROS_MASTER_URI: http://127.0.0.1:11311
  stdin_open: true
  network_mode: host
  privileged: true
  tty: true
  command: /bin/bash -c "source /root/.bashrc; cd /root/catkin_ws; catkin_make; source devel/setup.bash;  tail -f /dev/null "
