version: '2.4'
services:
  amr-base:
    image: amr_miniprj:1.0
    runtime: nvidia
    environment:
        ROS_IP: 127.0.0.1
        ROS_HOSTNAME: 127.0.0.1
        ROS_MASTER_URI: http://127.0.0.1:11311
        DISPLAY: $DISPLAY
        QT_X11_NO_MITSHM: '1'
        NVIDIA_VISIBLE_DEVICES: all
        NVIDIA_DRIVER_CAPABILITIES: compute,video,utility,graphics
    network_mode: host
    privileged: true
    stdin_open: true
    volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix
        - $HOME/.Xauthority:/root/.Xauthority
    command: roslaunch turtlebot3_gazebo turtlebot3_empty_world.launch
